modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="spiritualism"
version="1.0.0"
displayName="Spiritualism"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Валерия Худякова, MCreator"

[[dependencies.spiritualism]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




